--- #YAML:1.0
name: Win32
abstract: Interfaces to some Win32 API Functions
version: 0.56
author:
  - Jan Dubois <jan@jandubois.com>
license: perl
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl-libwin32/win32
  bugtracker: https://github.com/perl-libwin32/win32/issues
  MailingList: https://www.nntp.perl.org/group/perl.libwin32/
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
